#!/usr/bin/env python
# coding:utf8
"""
Django settings for one_finger project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import djcelery
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j%96gx(g6)*sn^5(br1=5&$s9i2njp)visj3alox5)23v*9lp#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'asset',
    'basic_service',
    'storage',
    'openstack',
    'one_finger',
    'check',
    'event',
    'alarm',
    # 'djcelery',
    # 'kombu.transport.django',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'one_finger.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'one_finger.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'e2',
        # 'NAME': 'one_finger',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# config login url
LOGIN_URL = '/login/'

# this is a static file dir
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

LOG_DIR = '/var/log/one_finger/one_finger.log'

# 是否启用ceph
CEPH_ENABLED = True

# 设置访问的url
ACCEPT_URL = 'publicurl'

# 设置regin
REGION = 'RegionOne'

# 设置neutron 使用什么模式
# 可选: neutron_linuxbridge_agent, neutron_openvswitch_agent
NEUTRON_RIVER_TYPE = 'neutron_linuxbridge_agent'


event_type = {
    'ceph': ['ceph_mon', 'ceph_osd'],
    'openstack': ['neutron', 'nova', 'cinder'],
    'mysql': [],
    'redis': [],
    'rabbitmq': [],
    'pacemaker': [],
    'basic_service': []
}

# 配置报警类型，多个使用列表方式[]
# 报警类型: email, we_chat, phone
# ['email', 'we_chat, 'phone']
ALARM_TYPE = 'email'

# 发送邮件设置
MAIL_USER = 'alarm@awcloud.com'
MAIL_PASSWORD = 'awcloud_123'

# 设置mail服务器的地址
MAIL_SERVER = 'smtp.exmail.qq.com:25'

# 邮箱收件人
NOTIFIER = 'zhaogl@awcloud.com'

MAIL_HEARD = u'创客测试环境报警  %(level)s'
#MAIL_HEARD = u'chuang ke xiang mu status %(level)s'
